name: GitHub Single Change 
'on': workflow_dispatch
jobs:
  # integrationTest:
  #   name: IntegrationTests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Register Artifact
  #       uses: ServiceNow/servicenow-devops-register-artifact@dev
  #       with:
  #         devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
  #         devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
  #         instance-url: '${{ secrets.SN_INSTANCE_NAME }}'
  #         tool-id: '${{ secrets.SN_ORCHESTRATION_TOOL_ID }}'
  #         context-github: '${{ toJSON(github) }}'
  #         job-name: IntegrationTests
  #         artifacts: ' [{"name": "com:autoclaim","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'
  #     - name: Register Package
  #       uses: ServiceNow/servicenow-devops-register-package@dev
  #       with:
  #         devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
  #         devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
  #         instance-url: '${{ secrets.SN_INSTANCE_NAME }}'
  #         tool-id: '${{ secrets.SN_ORCHESTRATION_TOOL_ID }}'
  #         context-github: '${{ toJSON(github) }}'
  #         job-name: IntegrationTests
  #         artifacts: ' [{"name": "com:autoclaim","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'
  #         package-name: autoclaim.war
  deploy:
    name: Deploy
    # needs: integrationTest
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow DevOps Change Automation
        uses: ServiceNow/servicenow-devops-change@dev
        with:
          instance-url: '${{ secrets.SN_INSTANCE_NAME }}'
          # devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
          # devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
          devops-integration-token: ${{ secrets.SN_INSTANCE_TOKEN }}
          tool-id: '${{ secrets.SN_ORCH_TOOL_ID }}'
          job-name: Deploy
          context-github: '${{ toJSON(github) }}'
          timeout: 3600
          interval: 100
          change-request: >-
            { "setCloseCode": "true", "attributes": { "short_description":
            "Automated test Software Deployment", "chg_model":
            "adffaa9e4370211072b7f6be5bb8f2ed", "description": "Automated
            Software Deployment.", "assignment_group":
            "a715cd759f2002002920bde8132e7018", "implementation_plan": "Software
            update is tested and results can be found in Test Summaries Tab.",
            "backout_plan": "When software fails in production, the previous
            software release will be re-deployed.", "test_plan": "Testing if the
            software was successfully deployed" } }
